# NumPy Mastery – Level 1: Arrays & Indexing

Build confidence through practice.

In [187]:
import numpy as np
arr = np.array([12,25,18,40,35,50,28,60,15,45])
arr

array([12, 25, 18, 40, 35, 50, 28, 60, 15, 45])

## Quick Revision
- dtype
- shape
- size
- indexing starts from 0
- negative indexing starts from -1

## Problem 1
**Task:** Print the complete array.

In [188]:
arr

array([12, 25, 18, 40, 35, 50, 28, 60, 15, 45])

## Problem 2
**Task:** Print the datatype of the array.

In [189]:
# Write your solution here
print(arr,arr.dtype)

[12 25 18 40 35 50 28 60 15 45] int64


## Problem 3
**Task:** Print the shape of the array.

In [190]:
# Write your solution here
print(arr,arr.dtype,arr.shape)

[12 25 18 40 35 50 28 60 15 45] int64 (10,)


## Problem 4
**Task:** Print the number of elements.

In [191]:

# Write your solution here
print("Write the Wrong answers")
no = arr.flatten().shape
print(no)
print("Here is the answers")
arr.size


Write the Wrong answers
(10,)
Here is the answers


10

## Problem 5
**Task:** Print the first element.

In [192]:
# Write your solution here
arr[0:5]

array([12, 25, 18, 40, 35])

## Problem 6
**Task:** Print the last element.

In [193]:
# Write your solution here
arr[-1]

np.int64(45)

## Problem 7
**Task:** Print the third element.

In [194]:
# Write your solution here
arr[2]

np.int64(18)

## Problem 8
**Task:** Print the first five elements.

In [195]:
# Write your solution here
arr[:5]

array([12, 25, 18, 40, 35])

## Problem 9
**Task:** Print the last four elements.

In [196]:
# Write your solution here
arr[-4:]

array([28, 60, 15, 45])

## Problem 10
**Task:** Print elements from index 2 to index 6.

In [197]:
# Write your solution here
arr[2:7]

array([18, 40, 35, 50, 28])

## Problem 11
**Task:** Print every second element.

In [198]:
# Write your solution here
arr[::2]

array([12, 18, 35, 28, 15])

## Problem 12
**Task:** Print every third element.

In [199]:
# Write your solution here
arr[::3]

array([12, 40, 28, 45])

## Problem 13
**Task:** Reverse the array.

In [200]:
# Write your solution here
arr[::-1]

array([45, 15, 60, 28, 50, 35, 40, 18, 25, 12])

## Problem 14
**Task:** Print the middle element (don't hardcode).

In [201]:
# Write your solution here
x = int(len(arr)/2)
arr[x]

np.int64(50)

## Problem 15
**Task:** Print only the even-index elements.

In [202]:
# Write your solution here
arr[1::2]

array([25, 40, 50, 60, 45])

## Problem 16
**Task:** Print only the odd-index elements.

In [203]:
# Write your solution here
arr[2::2]


array([18, 35, 28, 15])

## Problem 17
**Task:** Print the first three elements in reverse order.

In [204]:
# Write your solution here
arr[2::-1]

array([18, 25, 12])

## Problem 18
**Task:** Print the last five elements.

In [205]:
# Write your solution here
arr[5:]

array([50, 28, 60, 15, 45])

## Problem 19
**Task:** Print everything except the first element.

In [206]:
# Write your solution here
arr[1:]

array([25, 18, 40, 35, 50, 28, 60, 15, 45])

## Problem 20
**Task:** Print everything except the last element.

In [207]:
# Write your solution here
arr[0:-1]

array([12, 25, 18, 40, 35, 50, 28, 60, 15])

In [219]:
# Write your solution here
arr = np.array([12, 25, 18, 40, 35, 50, 28, 60, 15, 45])

original = arr.copy()



## Problem 21
**Task:** Change the first element to 100.

In [208]:
# Write your solution here
arr[0] = 100
arr 

array([100,  25,  18,  40,  35,  50,  28,  60,  15,  45])

## Problem 22
**Task:** Change the last element to 999.

In [209]:
# Write your solution here
arr[-1] = 999
arr

array([100,  25,  18,  40,  35,  50,  28,  60,  15, 999])

## Problem 23
**Task:** Change every element to 0.

In [210]:
# Write your solution here
arr[0:] = 0
arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Problem 24
**Task:** Reset the array to its original values.

In [221]:
arr = original
arr

array([12, 25, 18, 40, 35, 50, 28, 60, 15, 45])

## Problem 25
**Task:** Multiply every element by 2.

In [236]:
# Write your solution here
arr*2

array([ 24,  50,  36,  80,  70, 100,  56, 120,  30,  90])

## Problem 26
**Task:** Add 10 to every element.

In [238]:
# Write your solution here
arr
arr + 10 

array([22, 35, 28, 50, 45, 60, 38, 70, 25, 55])

## Problem 27
**Task:** Subtract 5 from every element.

In [239]:
# Write your solution here
arr - 5

array([ 7, 20, 13, 35, 30, 45, 23, 55, 10, 40])

## Problem 28
**Task:** Divide every element by 2.

In [240]:
# Write your solution here
arr/2

array([ 6. , 12.5,  9. , 20. , 17.5, 25. , 14. , 30. ,  7.5, 22.5])

## Problem 29
**Task:** Square every element.

In [241]:
# Write your solution here
arr **2

array([ 144,  625,  324, 1600, 1225, 2500,  784, 3600,  225, 2025])

## Problem 30
**Task:** Cube every element.

In [242]:
# Write your solution here
arr ** 3

array([  1728,  15625,   5832,  64000,  42875, 125000,  21952, 216000,
         3375,  91125])

## Challenge
Create `[10,20,30,40,50]` using a single NumPy function if possible.

In [243]:
# Your solution
arr = np.array([10,20,30,40,50])
arr


array([10, 20, 30, 40, 50])

## Reflection
1. Which problem was hardest?
2. Confidence (1-10)?
3. What will you revise?