# NumPy Mastery
# Notebook 02 - Slicing Mastery

## Mission
Master NumPy slicing until it becomes second nature.

## Quick Revision

### Slicing Syntax

```python
arr[start:stop:step]
```

- **start** → Included
- **stop** → Excluded
- **step** → Jump size
- Negative step means reverse direction.


In [2]:
import numpy as np

arr = np.array([10,20,30,40,50,60,70,80,90,100])
arr

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

## Warm-up (Problems 1-10)

### Problem 1
**Task:** Print 10 20 30

In [42]:
# Write your solution here
arr[0:3]

array([10, 20, 30])

### Problem 2
**Task:** Print 40 50 60

In [44]:
# Write your solution here
arr[3:6]

array([40, 50, 60])

### Problem 3
**Task:** Print 80 90 100

In [46]:
# Write your solution here
arr[7:11]

array([ 80,  90, 100])

### Problem 4
**Task:** Print 20 30 40 50

In [47]:
# Write your solution here
arr[1:5]

array([20, 30, 40, 50])

### Problem 5
**Task:** Print 70 80

In [49]:
# Write your solution here
arr[6:8]

array([70, 80])

### Problem 6
**Task:** Print 10 30 50 70 90

In [50]:
# Write your solution here
arr[0:9:2]

array([10, 30, 50, 70, 90])

### Problem 7
**Task:** Print 20 40 60 80 100

In [51]:
# Write your solution here
arr[1::2]

array([ 20,  40,  60,  80, 100])

### Problem 8
**Task:** Reverse the array

In [52]:
# Write your solution here
arr[::-1]

array([100,  90,  80,  70,  60,  50,  40,  30,  20,  10])

### Problem 9
**Task:** Print 100 80 60 40 20

In [53]:
# Write your solution here
arr[-1::-2]

array([100,  80,  60,  40,  20])

### Problem 10
**Task:** Print 90 70 50 30 10

In [54]:
# Write your solution here
arr[-2::-2]

array([90, 70, 50, 30, 10])

## Easy Problems

### Problem 11
**Task:** Print everything except the first element.

In [55]:
# Write your solution here
arr[1::]

array([ 20,  30,  40,  50,  60,  70,  80,  90, 100])

### Problem 12
**Task:** Print everything except the last element.

In [58]:
# Write your solution here
arr[0:9:]

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

### Problem 13
**Task:** Print the first half of the array.

In [60]:
# Write your solution here
arr[0:int(len(arr)/2)]

array([10, 20, 30, 40, 50])

### Problem 14
**Task:** Print the second half of the array.

In [61]:
# Write your solution here
arr[int(len(arr)/2)::]

array([ 60,  70,  80,  90, 100])

### Problem 15
**Task:** Print the middle four elements.

In [67]:
# Write your solution here
x = int(len(arr)/2-2)
y = int(len(arr)/2+2)
arr[x:y]


array([40, 50, 60, 70])

### Problem 16
**Task:** Print every third element.

In [68]:
# Write your solution here
arr[::3]

array([ 10,  40,  70, 100])

### Problem 17
**Task:** Print every fourth element.

In [70]:
# Write your solution here
arr[::4]

array([10, 50, 90])

### Problem 18
**Task:** Print the array from right to left skipping every second element.

In [71]:
# Write your solution here
arr[-1::-2]

array([100,  80,  60,  40,  20])

### Problem 19
**Task:** Print only the first five elements in reverse order.

In [81]:
# Write your solution here
arr[5::-1]

array([60, 50, 40, 30, 20, 10])

### Problem 20
**Task:** Print only the last five elements in reverse order.

In [83]:
# Write your solution here
arr[10:4:-1]

array([100,  90,  80,  70,  60])

## Medium Problems

### Problem 21
**Task:** Swap the first half with the second half using slicing.

In [90]:
# Write your solution here
original = arr.copy()
original[0:5:] = arr[5::]
original

array([ 60,  70,  80,  90, 100,  60,  70,  80,  90, 100])

### Problem 22
**Task:** Print every second element from index 2.

In [91]:
# Write your solution here
arr[2::2]

array([30, 50, 70, 90])

### Problem 23
**Task:** Print every second element till index 8.

In [92]:
# Write your solution here
arr[:8:2]

array([10, 30, 50, 70])

### Problem 24
**Task:** Print all elements except the first and last.

In [94]:
# Write your solution here.
arr[1:int(len(arr)-1):]

array([20, 30, 40, 50, 60, 70, 80, 90])

### Problem 25
**Task:** Print all elements except the first two and last two.

In [95]:
# Write your solution here
arr[2:int(len(arr)-2):]

array([30, 40, 50, 60, 70, 80])

### Problem 26
**Task:** Print the array in groups of two (display slices).

In [ ]:
# Write your solution here


### Problem 27
**Task:** Print alternate elements in reverse.

In [103]:
# Write your solution here
arr[:0:-2]

array([100,  80,  60,  40,  20])

### Problem 28
**Task:** Print the center six elements.

In [105]:
# Write your solution here.
arr[int(len(arr)/2-3):int(len(arr)/2+3)]

array([30, 40, 50, 60, 70, 80])

### Problem 29
**Task:** Create a new array containing only odd-position values.

In [124]:
# Write your solution here
new_arr = arr[0::2]
new_arr

array([10, 30, 50, 70, 90])

### Problem 30
**Task:** Create a new array containing only even-position values.

In [125]:
# Write your solution here
new_arr = arr[1::2]
new_arr


array([ 20,  40,  60,  80, 100])

## Hard Problems

### Problem 31
**Task:** Without loops, reverse only the middle six elements.

In [ ]:
# Write your solution here
arr[int(len(arr)/2+3):int(len(arr)/2-2):-1]



array([90, 80, 70, 60, 50])

### Problem 32
**Task:** Reverse only the first half.

In [133]:
# Write your solution here
arr[int((len(arr)/2)-1)::-1]

array([50, 40, 30, 20, 10])

### Problem 33
**Task:** Reverse only the second half.

In [136]:
# Write your solution here
arr[:int((len(arr)/2)-1):-1]


array([100,  90,  80,  70,  60])

### Problem 34
**Task:** Using negative indexing only, print 30 40 50 60 70.

In [142]:
# Write your solution here
arr[-4:1:-1]

array([70, 60, 50, 40, 30])

### Problem 35
**Task:** Without changing the original array, create 100 90 80 70 60.

In [150]:
# Write your solution here
new_arr = arr[-1:4:-1]
new_arr

array([100,  90,  80,  70,  60])

# 🏆 Boss Challenge

```python
sales = np.array([1200,1400,1600,1800,2000,
                  2200,2400,2600,2800,3000])
```

Using **only slicing**, create:

1. First Quarter
2. Second Quarter
3. Weekend Sales
4. Reverse Sales
5. Alternate Sales
6. Middle Four Sales
7. Everything except first and last
8. Last Three Sales
9. Reverse first five sales
10. Reverse last five sales


In [177]:
# Boss Challenge Solution
sales = np.array([1200,1400,1600,1800,2000,
                  2200,2400,2600,2800,3000])
print("First Quarter:- ",sales[0:int(len(sales)/4):])
print("Second Quarter:- ",sales[int(len(sales)/4):int(len(sales)/2)])
print("Weekly Sales:- ",sales[0:8:].sum())
print("Reverse Sales:- ",sales[::-1] )
print("Alternate Sales :- ",sales[0::2])
print("Middle four Sales:- ",sales[int(len(sales)/2-2):int(len(sales)/2+3)])
print("Except Last ans First: - ",sales[1:int(len(sales)-1):])
print("Reverse first 5 Sales :- ",sales[4::-1])
print("Reverse first 5 Sales :- ",sales[int(len(sales)):4:-1])

First Quarter:-  [1200 1400]
Second Quarter:-  [1600 1800 2000]
Weekly Sales:-  15200
Reverse Sales:-  [3000 2800 2600 2400 2200 2000 1800 1600 1400 1200]
Alternate Sales :-  [1200 1600 2000 2400 2800]
Middle four Sales:-  [1800 2000 2200 2400 2600]
Except Last ans First: -  [1400 1600 1800 2000 2200 2400 2600 2800]
Reverse first 5 Sales :-  [2000 1800 1600 1400 1200]
Reverse first 5 Sales :-  [3000 2800 2600 2400 2200]


# Interview Questions

1. What is slicing?
2. Why is the stop index excluded?
3. Difference between indexing and slicing?
4. What happens when step is negative?
5. Does slicing return a view or a copy?


# Reflection

- What was the hardest problem?
- Which slicing pattern do you need to revise?
- Confidence (1-10):
