# 📘 NumPy Mastery
# Notebook 03 — Boolean Indexing

## 🎯 Mission
Learn how to filter data efficiently using Boolean Indexing.

By the end of this notebook you should be able to:
- Filter data using conditions
- Combine multiple conditions
- Replace values using Boolean masks
- Solve real-world filtering problems

---
### ⭐ Quick Revision

Comparison Operators

- `>`
- `<`
- `>=`
- `<=`
- `==`
- `!=`

Boolean Operators

- `&` → AND
- `|` → OR
- `~` → NOT

Remember:
- Use **parentheses** around each condition.


In [68]:
import numpy as np

marks = np.array([35, 78, 91, 45, 67, 89, 23, 56, 99, 40])
marks

array([35, 78, 91, 45, 67, 89, 23, 56, 99, 40])

## ⚠️ Common Mistakes

❌ `marks > 40 and marks < 80`

✅ `(marks > 40) & (marks < 80)`

---

❌ Using loops for filtering.

✅ Use Boolean Indexing whenever possible.


## 🟢 Warm-up (Problems 1–10)

### Problem 1
⭐ Task: Print marks greater than 50.

In [69]:
# Write your solution here
marks[marks>50]

array([78, 91, 67, 89, 56, 99])

### Problem 2
⭐ Task: Print marks less than 50.

In [70]:
# Write your solution here
marks[marks<50]

array([35, 45, 23, 40])

### Problem 3
⭐ Task: Print marks equal to 40.

In [71]:
# Write your solution here
marks[marks ==40]

array([40])

### Problem 4
⭐ Task: Print marks greater than or equal to 60.

In [72]:
# Write your solution here
marks[marks>=60]

array([78, 91, 67, 89, 99])

### Problem 5
⭐ Task: Print marks less than or equal to 35.

In [73]:
# Write your solution here
marks[marks<=35]

array([35, 23])

### Problem 6
⭐ Task: Print marks not equal to 45.

In [74]:
# Write your solution here
marks[marks!=45]

array([35, 78, 91, 67, 89, 23, 56, 99, 40])

### Problem 7
⭐ Task: Count students scoring above 70.

In [75]:
# Write your solution here
len(marks[marks>70])

4

### Problem 8
⭐ Task: Count students below 40.

In [76]:
# Write your solution here
len(marks[marks<40])

2

### Problem 9
⭐ Task: Print passed students (>=40).

In [77]:
# Write your solution here.
print("This students are pass in exam :-",marks[marks>=40])

This students are pass in exam :- [78 91 45 67 89 56 99 40]


### Problem 10
⭐ Task: Print failed students (<40).

In [78]:
# Write your solution here
print("This are the studennt who failed in exam :- ",marks[marks<40])

This are the studennt who failed in exam :-  [35 23]


## 🟡 Easy (Problems 11–20)

### Problem 11
⭐ Task: Print marks between 40 and 80.

In [79]:
# Write your solution here
marks[(marks>40)&(marks<80)]

array([78, 45, 67, 56])

### Problem 12
⭐ Task: Print marks above the average.

In [80]:
# Write your solution here
marks.sum()/int(len(marks))

np.float64(62.3)

### Problem 13
⭐ Task: Print marks below the average.

In [81]:
# Write your solution here
marks[marks<marks.sum()/int(len(marks))]

array([35, 45, 23, 56, 40])

### Problem 14
⭐ Task: Print even marks only.

In [82]:
# Write your solution here
marks[marks%2==0]

array([78, 56, 40])

### Problem 15
⭐ Task: Print odd marks only.

In [83]:
# Write your solution here
marks[marks%2!=0]

array([35, 91, 45, 67, 89, 23, 99])

### Problem 16
⭐ Task: Replace failed marks with 40.

In [109]:
# Write your solution here
original_marks = marks.copy()
marks[marks<40] = 40
marks


array([40, 78, 91, 45, 67, 89, 40, 56, 99, 40])

### Problem 17
⭐ Task: Replace marks above 90 with 90.

In [111]:
# Write your solution here
marks[(marks>90)] = 90
marks

array([40, 78, 90, 45, 67, 89, 40, 56, 90, 40])

### Problem 18
⭐ Task: Count students above 80.

In [112]:
# Write your solution here
len(marks[marks>80])

3

### Problem 19
⭐ Task: Count students below 60.

In [116]:
# Write your solution here
len(marks[marks<60])

5

### Problem 20
⭐ Task: Print top scorers (>85).

In [117]:
# Write your solution here
marks[marks>85]

array([90, 89, 90])

## 🟠 Medium (Problems 21–30)

In [118]:
salary = np.array([
25000,32000,45000,60000,72000,
85000,40000,52000,90000,31000
])

### Problem 21
⭐ Task: Use the salary dataset below.

In [119]:
# Write your solution here
salary

array([25000, 32000, 45000, 60000, 72000, 85000, 40000, 52000, 90000,
       31000])

### Problem 22
⭐ Task: Print salary above ₹50,000.

In [120]:
# Write your solution here
salary[salary>50000]

array([60000, 72000, 85000, 52000, 90000])

### Problem 23
⭐ Task: Print salary below ₹40,000.

In [121]:
# Write your solution here
salary[salary<40000]

array([25000, 32000, 31000])

### Problem 24
⭐ Task: Count employees above ₹60,000.

In [122]:
# Write your solution here
len(salary[salary>60000])

3

### Problem 25
⭐ Task: Replace salaries below ₹30,000 with ₹30,000.

In [126]:
# Write your solution here
original_salary = salary.copy()
salary[salary<30000] = 30000
salary

array([30000, 32000, 45000, 60000, 72000, 85000, 40000, 52000, 90000,
       31000])

### Problem 26
⭐ Task: Print salaries between ₹40,000 and ₹80,000.

In [127]:
# Write your solution here
salary[(salary<80000)&(salary>40000)]

array([45000, 60000, 72000, 52000])

### Problem 27
⭐ Task: Print highest earners (>₹80,000).

In [128]:
# Write your solution here
salary[salary>80000]

array([85000, 90000])

### Problem 28
⭐ Task: Print salaries not equal to ₹45,000.

In [129]:
# Write your solution here
salary[salary!=45000]

array([30000, 32000, 60000, 72000, 85000, 40000, 52000, 90000, 31000])

### Problem 29
⭐ Task: Count employees earning more than the average.

In [130]:
# Write your solution here
salary[salary>salary.sum()/int(len(salary))]

array([60000, 72000, 85000, 90000])

### Problem 30
⭐ Task: Print employees earning less than the average.

In [131]:
# Write your solution here
salary[salary<salary.sum()/int(len(salary))]


array([30000, 32000, 45000, 40000, 52000, 31000])

## 🔴 Hard (Problems 31–35)

In [132]:
temperature = np.array([
32,35,41,39,28,
30,45,38,42,36
])

### Problem 31
⭐ Task: Use the temperature dataset below.

In [133]:
# Write your solution here
temperature

array([32, 35, 41, 39, 28, 30, 45, 38, 42, 36])

### Problem 32
⭐ Task: Print temperatures above 40°C.

In [134]:
# Write your solution here
temperature[temperature>40]

array([41, 45, 42])

### Problem 33
⭐ Task: Replace temperatures below 30°C with 30°C.

In [138]:
# Write your solution here
original_temerature = temperature.copy()
temperature[temperature<30] = 30
temperature

array([32, 35, 41, 39, 30, 30, 45, 38, 42, 36])

### Problem 34
⭐ Task: Count hot days (>38°C).

In [140]:
# Write your solution here
len(temperature[temperature>38])

4

### Problem 35
⭐ Task: Print temperatures that are multiples of 5.

In [141]:
# Write your solution here
temperature[temperature%5==0]

array([35, 30, 30, 45])

# 🏆 Boss Challenge

```python
students = np.array([78,45,91,23,67,88,39,59,95,72])
```

Using only Boolean Indexing:

1. Print passed students.
2. Print failed students.
3. Print students above 80.
4. Print students below average.
5. Replace failed marks with 40.
6. Count distinction students (>75).
7. Count students below 50.
8. Print only even marks.
9. Print only odd marks.
10. Print marks between 60 and 90.


In [146]:
students = np.array([78,45,91,23,67,88,39,59,95,72])
# Boss Challenge Solution
print("Here are the pass student name :-",students[students>40])
print("here are the list of failed Student:-",students[students<40])
print("Here is the studnet above 80:- ",students[students>80])
print("Below avrage marks:-",students[students<students.sum()/int(len(students))])
students[students<40]=40
print("Rplace the failed student with 40marks",students)
print("Numbr of distinction student",students[students>75])
print("No of student Below 50",students[students<50])
print("Even number only", students[students%2==0])
print("odd number only", students[students%2!=0])
print("Marks between 60 and 90",students[(students>60)&(students<90)])

Here are the pass student name :- [78 45 91 67 88 59 95 72]
here are the list of failed Student:- [23 39]
Here is the studnet above 80:-  [91 88 95]
Below avrage marks:- [45 23 39 59]
Rplace the failed student with 40marks [78 45 91 40 67 88 40 59 95 72]
Numbr of distinction student [78 91 88 95]
No of student Below 50 [45 40 40]
Even number only [78 40 88 40 72]
odd number only [45 91 67 59 95]
Marks between 60 and 90 [78 67 88 72]


# 🎤 Interview Questions

1. What is Boolean Indexing?
2. Why is it faster than loops?
3. Difference between `&` and `and`?
4. Why are parentheses required?
5. What does a Boolean mask contain?

---

# 📝 Reflection

- Which problem was hardest?
- Which mistake did you repeat?
- Confidence (1–10):
- Notes:
