# 📘 NumPy Mastery
# Notebook 04 – Array Operations & Statistics

## 🎯 Mission
Master NumPy arithmetic operations and statistics.

## Quick Revision

Functions:
- sum()
- mean()
- min()
- max()
- std()
- var()
- prod()
- cumsum()
- cumprod()


In [152]:
import numpy as np

marks = np.array([65,72,88,91,55,78,83,69,95,74])
marks

array([65, 72, 88, 91, 55, 78, 83, 69, 95, 74])

## Warm-up

### Problem 1
Find the sum.

In [153]:
# Write your solution here
marks.sum()

np.int64(770)

### Problem 2
Find the mean.

In [154]:
# Write your solution here
marks.mean()

np.float64(77.0)

### Problem 3
Find the maximum.

In [155]:
# Write your solution here
marks.max()

np.int64(95)

### Problem 4
Find the minimum.

In [156]:
# Write your solution here
marks.min()

np.int64(55)

### Problem 5
Find the product.

In [157]:
# Write your solution here
marks.prod()

np.int64(6473061270932256000)

### Problem 6
Add 5 to every element.

In [158]:
# Write your solution here
marks + 5

array([ 70,  77,  93,  96,  60,  83,  88,  74, 100,  79])

### Problem 7
Subtract 2.

In [159]:
# Write your solution here
marks - 2 

array([63, 70, 86, 89, 53, 76, 81, 67, 93, 72])

### Problem 8
Multiply by 2.

In [160]:
# Write your solution here
marks *2

array([130, 144, 176, 182, 110, 156, 166, 138, 190, 148])

### Problem 9
Divide by 2.

In [161]:
# Write your solution here
marks / 2

array([32.5, 36. , 44. , 45.5, 27.5, 39. , 41.5, 34.5, 47.5, 37. ])

### Problem 10
Square every element.

In [162]:
# Write your solution here
marks **2 

array([4225, 5184, 7744, 8281, 3025, 6084, 6889, 4761, 9025, 5476])

## Core Practice

### Problem 11
Find standard deviation.

In [163]:
# Write your solution here
marks.std()

np.float64(11.8490505948789)

### Problem 12
Find variance.

In [164]:
# Write your solution here
marks.var()

np.float64(140.4)

### Problem 13
Find cumulative sum.

In [165]:
# Write your solution here
marks.cumsum()

array([ 65, 137, 225, 316, 371, 449, 532, 601, 696, 770])

### Problem 14
Find cumulative product.

In [166]:
# Write your solution here
marks.cumprod()

array([                 65,                4680,              411840,
                  37477440,          2061259200,        160778217600,
            13344592060800,     920776852195200,   87473800958544000,
       6473061270932256000])

### Problem 15
Average of marks above 80.

In [167]:
# Write your solution here
marks[marks>80].mean()

np.float64(89.25)

### Problem 16
Total of marks below 70.

In [168]:
# Write your solution here
marks[marks<70].sum()

np.int64(189)

### Problem 17
Increase marks below 60 by 10.

In [169]:
# Write your solution here
marks[marks<60] + 10

array([65])

### Problem 18
Decrease marks above 90 by 5.

In [170]:
# Write your solution here
marks[marks>90] -5 

array([86, 90])

### Problem 19
Find range (max-min).

In [171]:
# Write your solution here
range  = marks.max() - marks.min()
range

np.int64(40)

### Problem 20
Normalize marks using max.

In [172]:
# Write your solution here
marks/marks.max()

array([0.68421053, 0.75789474, 0.92631579, 0.95789474, 0.57894737,
       0.82105263, 0.87368421, 0.72631579, 1.        , 0.77894737])

### Problem 21
Percentage contribution of each mark.

In [173]:
# Write your solution here
(marks/marks.sum())*100

array([ 8.44155844,  9.35064935, 11.42857143, 11.81818182,  7.14285714,
       10.12987013, 10.77922078,  8.96103896, 12.33766234,  9.61038961])

### Problem 22
Replace below-average marks with average.

In [174]:
# Write your solution here
orignal_marks = marks
marks[marks<marks.mean()] = marks.mean()
marks
# orignal_marks

array([77, 77, 88, 91, 77, 78, 83, 77, 95, 77])

### Problem 23
Create doubled array.

In [175]:
# Write your solution here
double_marks = marks * 2
double_marks

array([154, 154, 176, 182, 154, 156, 166, 154, 190, 154])

### Problem 24
Create squared array.

In [176]:
# Write your solution here
marks ** 2

array([5929, 5929, 7744, 8281, 5929, 6084, 6889, 5929, 9025, 5929])

### Problem 25
Round average to 2 decimals.

In [177]:
# Write your solution here
marks.round(2)

array([77, 77, 88, 91, 77, 78, 83, 77, 95, 77])

## Real World

In [178]:
sales = np.array([1200,1450,1320,1680,1750,1900,2100,2050,1980,2200])

### Problem 26
Find total sales.

In [179]:
# Write your solution here
sales.sum()

np.int64(17630)

### Problem 27
Find average sales.

In [180]:
# Write your solution here
sales.mean()

np.float64(1763.0)

### Problem 28
Find highest sales.

In [181]:
# Write your solution here
sales.max()

np.int64(2200)

### Problem 29
Find lowest sales.

In [182]:
# Write your solution here
sales.min()

np.int64(1200)

### Problem 30
Find cumulative sales.

In [183]:
# Write your solution here
sales.cumsum()

array([ 1200,  2650,  3970,  5650,  7400,  9300, 11400, 13450, 15430,
       17630])

### Problem 31
Increase sales by 10%.

In [184]:
# Write your solution here
sales + sales*0.10

array([1320., 1595., 1452., 1848., 1925., 2090., 2310., 2255., 2178.,
       2420.])

### Problem 32
Calculate 20% profit.

In [185]:
# Write your solution here
sales - sales*0.20

array([ 960., 1160., 1056., 1344., 1400., 1520., 1680., 1640., 1584.,
       1760.])

### Problem 33
Sales above average.

In [186]:
# Write your solution here
sales[sales>sales.mean()]

array([1900, 2100, 2050, 1980, 2200])

### Problem 34
Sales below average.

In [187]:
# Write your solution here
sales[sales<sales.mean()]


array([1200, 1450, 1320, 1680, 1750])

### Problem 35
Difference from average.

In [188]:
# Write your solution here
sales - sales.mean()

array([-563., -313., -443.,  -83.,  -13.,  137.,  337.,  287.,  217.,
        437.])

## Hard

### Problem 36
Calculate z-score.

In [189]:
# Write your solution here
(sales - sales.mean())/sales.std()

array([-1.72032948, -0.95641763, -1.35365179, -0.25361873, -0.03972342,
        0.41862369,  1.02975317,  0.8769708 ,  0.66307548,  1.33531791])

### Problem 37
Replace outliers with mean.

In [190]:
# Write your solution here
sales[(sales - sales.mean())/sales.std()>3]


array([], dtype=int64)

### Problem 38
Find cumulative average.

In [191]:
# Write your solution here
sales.cumsum()/(np.arange(1,int(len(sales))+1))

array([1200.        , 1325.        , 1323.33333333, 1412.5       ,
       1480.        , 1550.        , 1628.57142857, 1681.25      ,
       1714.44444444, 1763.        ])

### Problem 39
Compare marks with class average.

In [192]:
# Write your solution here
marks - marks.mean()

array([-5., -5.,  6.,  9., -5., -4.,  1., -5., 13., -5.])

### Problem 40
Performance score = marks*0.7 + 10.

In [193]:
# Write your solution here
marks*0.7 +10

array([63.9, 63.9, 71.6, 73.7, 63.9, 64.6, 68.1, 63.9, 76.5, 63.9])

# 🏆 Boss Challenge

Use only NumPy to:
1. Find total, average, min and max.
2. Identify above-average values.
3. Increase below-average values.
4. Compute cumulative sum.
5. Compute cumulative product.
6. Calculate standard deviation and variance.
7. Normalize the data.
8. Solve everything without loops.


In [194]:
# Boss Challenge
marks = np.array([65,72,88,91,55,78,83,69,95,74])
sales = np.array([1200,1450,1320,1680,1750,1900,2100,2050,1980,2200])
print("Marks","\t","Sales")
print(marks.sum(),"\t",sales.sum())
print(marks.mean(),"\t",sales.mean())
sales[sales<sales.mean()] = sales.mean()
marks[marks<marks.mean()] = marks.mean()
print(marks,"\t",sales)
print(marks.cumsum(),"\t",sales.cumsum())
print(marks.cumprod(),"\t",sales.cumprod())
print(marks.std(),"\t",sales.std())
print(marks.var(),"\t",sales.var())
print(marks/marks.mean(),"\t",sales/sales.mean())


Marks 	 Sales
770 	 17630
77.0 	 1763.0
[77 77 88 91 77 78 83 77 95 77] 	 [1763 1763 1763 1763 1763 1900 2100 2050 1980 2200]
[ 77 154 242 333 410 488 571 648 743 820] 	 [ 1763  3526  5289  7052  8815 10715 12815 14865 16845 19045]
[                  77                 5929               521752
             47479432           3655916264         285161468592
       23668401893136     1822466945771472   173134359848289840
 -5115398365391233936] 	 [                1763              3108169           5479701947
        9660714532561    17031839720905043 -4532992677699521532
  -764681134866583344   376919788816032160  8431418907361612160
 -8302941956262173696]
6.54217089351845 	 158.91585823950987
42.8 	 25254.25
[0.93902439 0.93902439 1.07317073 1.1097561  0.93902439 0.95121951
 1.01219512 0.93902439 1.15853659 0.93902439] 	 [0.92570228 0.92570228 0.92570228 0.92570228 0.92570228 0.99763718
 1.10265161 1.076398   1.03964295 1.15515883]


# Reflection

- Hardest problem:
- Confidence (1-10):
- Notes:
