# 📘 NumPy Mastery
# Notebook 05 – Reshape, Broadcasting & Stacking

## 🎯 Mission
Learn reshape, broadcasting and stacking.

## Topics
- reshape()
- flatten()
- ravel()
- transpose (.T)
- concatenate()
- hstack()
- vstack()
- split()
- Broadcasting

In [47]:
import numpy as np

arr = np.arange(1,13)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

## Common Mistakes
- reshape preserves total elements.
- flatten returns a copy.
- ravel usually returns a view.
- Broadcasting requires compatible shapes.

## Warm-up

### Problem 1
Reshape into (3,4).

In [48]:
# Write your solution here
arr = arr.reshape((3,4))

### Problem 2
Reshape into (2,6).

In [49]:
# Write your solution here
arr.reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

### Problem 3
Reshape into (4,3).

In [50]:
# Write your solution here
arr.reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

### Problem 4
Convert into a single row.

In [51]:
# Write your solution here
arr.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

### Problem 5
Convert into a single column.

In [52]:
# Write your solution here
arr.reshape((12,1))

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

### Problem 6
Flatten the array.

In [53]:
# Write your solution here
arr.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

### Problem 7
Use ravel().

In [54]:
# Write your solution here
arr.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

### Problem 8
Transpose a 3x4 array.

In [55]:
# Write your solution here
arr.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

### Problem 9
Find the shape before and after reshape.

In [56]:
# Write your solution here
arr.shape
arr = arr.reshape((12,1))
arr.shape


(12, 1)

### Problem 10
Print the number of dimensions.

In [57]:
# Write your solution here
arr.ndim

2

In [58]:
# Datasets for Concatenate / Stack / Split
arr1 = np.array([1,2,3,4,5,6])
arr2 = np.array([7,8,9,10,11,12])

matrix1 = np.array([[1,2,3],[4,5,6]])
matrix2 = np.array([[7,8,9],[10,11,12]])


## Core Practice

### Problem 11
Concatenate two arrays.

In [59]:
# Write your solution here
import numpy as np

arr1 = np.array([1, 2, 3, 4, 5, 6])

arr2 = np.array([7, 8, 9, 10, 11, 12])
np.concatenate((arr1,arr2),axis=0)
# np.concatenate((arr1,arr2),axis=1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

### Problem 12
Stack arrays horizontally.

In [60]:
# Write your solution here
np.hstack((arr1,arr2))


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

### Problem 13
Stack arrays vertically.

In [61]:
# Write your solution heren
np.vstack((arr1,arr2))

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

### Problem 14
Split into 3 equal parts.

In [96]:
# Write your solution here
np.split(arr1,3)

[array([1, 2]), array([3, 4]), array([5, 6])]

### Problem 15
Split into 4 equal parts.

In [97]:
# Write your solution here
np.split(arr,4)

[array([[1],
        [2],
        [3]]),
 array([[4],
        [5],
        [6]]),
 array([[7],
        [8],
        [9]]),
 array([[10],
        [11],
        [12]])]

### Problem 16
Broadcast +5.

In [99]:
# Write your solution here
matrix1 + 5


array([[ 6,  7,  8],
       [ 9, 10, 11]])

### Problem 17
Broadcast ×10.

In [100]:
# Write your solution here
matrix1 * 10

array([[10, 20, 30],
       [40, 50, 60]])

### Problem 18
Broadcast subtraction with another array.

In [101]:
# Write your solution here
arr1 - arr2

array([-6, -6, -6, -6, -6, -6])

### Problem 19
Reshape then flatten again.

In [105]:
# Write your solution here
arr = arr.reshape(3,4)
arr.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

### Problem 20
Compare flatten() and ravel().

In [108]:
# Write your solution here
print(arr.flatten())
print(arr.ravel())

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


### Problem 21
Use reshape(-1,3).

In [109]:
# Write your solution here
arr.reshape(-1,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

### Problem 22
Use reshape(3,-1).

In [110]:
# Write your solution here
arr.reshape(3,-1)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

### Problem 23
Create a 3×4 matrix.

In [115]:
# Write your solution here
matrix = np.array([[1,2,3,10],[4,5,6,11],[7,8,9,12]])
print(matrix,matrix.shape)

[[ 1  2  3 10]
 [ 4  5  6 11]
 [ 7  8  9 12]] (3, 4)


### Problem 24
Convert matrix back to 1D.

In [117]:
# Write your solution here
matrix.flatten()

array([ 1,  2,  3, 10,  4,  5,  6, 11,  7,  8,  9, 12])

### Problem 25
Find rows and columns after reshape.

In [118]:
# Write your solution here
matrix.shape

(3, 4)

## Real World

In [119]:
sales = np.array([1200,1450,1320,1680,1750,1900,2100,2050,1980,2200,2400,2600])

### Problem 26
Reshape monthly sales into quarters.

In [123]:
# Write your solution here
sales = sales.reshape(4,3)
sales

array([[1200, 1450, 1320],
       [1680, 1750, 1900],
       [2100, 2050, 1980],
       [2200, 2400, 2600]])

### Problem 27
Find quarterly totals.

In [125]:
# Write your solution here
sales.sum(axis=0)


array([7180, 7650, 7800])

### Problem 28
Increase every quarter by 10%.

In [128]:
# Write your solution here
sales + sales*0.10

array([[1320., 1595., 1452.],
       [1848., 1925., 2090.],
       [2310., 2255., 2178.],
       [2420., 2640., 2860.]])

### Problem 29
Stack two years of sales.

In [ ]:
# Write your solution here
sales = sales.reshape(2,6)

array([[1200, 1450, 1320, 1680, 1750, 1900],
       [2100, 2050, 1980, 2200, 2400, 2600]])

### Problem 30
Split yearly sales into halves.

In [130]:
np.split(sales,2)

[array([[1200, 1450, 1320],
        [1680, 1750, 1900]]),
 array([[2100, 2050, 1980],
        [2200, 2400, 2600]])]

### Problem 31
Broadcast 18% tax.

In [131]:
# Write your solution here
sales + 0.18*sales

array([[1416. , 1711. , 1557.6],
       [1982.4, 2065. , 2242. ],
       [2478. , 2419. , 2336.4],
       [2596. , 2832. , 3068. ]])

### Problem 32
Combine department sales.

In [ ]:
# Write your solution here


### Problem 33
Transpose sales matrix.

In [132]:
# Write your solution here
sales.T

array([[1200, 1680, 2100, 2200],
       [1450, 1750, 2050, 2400],
       [1320, 1900, 1980, 2600]])

### Problem 34
Flatten sales matrix.

In [135]:
# Write your solution here
sales = sales.flatten()

### Problem 35
Verify shapes.

In [136]:
# Write your solution here
sales.shape

(12,)

In [137]:
# Broadcasting datasets
matrix = np.array([[10,20,30],[40,50,60],[70,80,90]])
row = np.array([1,2,3])
column = np.array([[1],[2],[3]])

## Hard

### Problem 36
Broadcast row vector over matrix.

In [138]:
# Write your solution here
matrix + row

array([[11, 22, 33],
       [41, 52, 63],
       [71, 82, 93]])

### Problem 37
Broadcast column vector over matrix.

In [139]:
# Write your solution here
matrix + column

array([[11, 21, 31],
       [42, 52, 62],
       [73, 83, 93]])

### Problem 38
Create multiplication table using broadcasting.

In [140]:
# Write your solution here
arr = np.array([1,2,3,4,5,6,7,8,9,10])
arr * 2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

### Problem 39
Explain invalid broadcast.

In [ ]:
# Write your solution here


### Problem 40
Reshape challenge without hardcoding.

In [142]:
# Write your solution here
arr.reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

# 🏆 Boss Challenge

Use only NumPy to reshape, stack, split, broadcast and analyze the sales dataset without loops.

In [163]:
# Boss Challenge
np.split(sales,3)
sales = sales.reshape(4,3)
matrix = np.concatenate((matrix1,matrix2),axis= 1) 
matrix = matrix.reshape(4,3)
np.hstack((sales,matrix))
np.vstack((sales,matrix))
sales + 10
sales + matrix
sales.mean()

np.float64(1885.8333333333333)

# Reflection

- Hardest topic:
- Confidence (1-10):
- Notes: