# NumPy Mastery — Notebook 06
## Sorting, Searching & Statistical Analysis

### Mission
Strengthen the NumPy concepts you have already learned before moving to the final NumPy notebook.

**Important:** This notebook uses only concepts already covered in your NumPy study material. It does **not** require `np.where()`, `np.argsort()`, `np.searchsorted()`, or the `np.random` module.

### Learning pattern
**Quick Revision → Warm-up → Core Practice → Real World → Hard → Boss Challenge → Interview → Reflection**

The difficulty increases gradually, but the level stays close to the previous notebooks.

## 2. Quick Revision

### Array properties
- `shape` → shape of the array
- `size` → total number of elements
- `ndim` → number of dimensions
- `dtype` → data type

### Indexing & slicing
- Basic indexing
- 2D indexing
- Fancy indexing
- Boolean indexing
- Slicing
- Copy vs View

### Shape operations
- `reshape()`
- `flatten()`
- `ravel()`
- `transpose()`
- `hstack()`
- `vstack()`
- `concatenate()`
- `split()`
- `array_split()`

### Aggregation & statistics
- `sum()`
- `prod()`
- `min()`
- `max()`
- `argmin()`
- `argmax()`
- `mean()`
- `median()`
- `std()`
- `var()`

### Mathematical functions
- `square()`
- `sqrt()`
- `pow()`
- `abs()`
- `round()`
- `ceil()`
- `floor()`
- `trunc()`
- `log()`
- `log10()`
- `log2()`
- `exp()`

### Sorting & uniqueness
- `sort()`
- `unique()`

### Important reminder
`np.sort(arr)` returns a **sorted array**. It does not change the original array unless you assign the result back.

For example:

```python
sorted_arr = np.sort(arr)
```

## 3. Complete Datasets

Run this cell before starting the problems.

These datasets are designed so that every question in this notebook has enough information to solve it.

In [193]:
import numpy as np

# Student marks
marks = np.array([
    78, 65, 91, 45, 82,
    56, 99, 73, 68, 88,
    59, 77, 84, 93, 61,
    70, 80, 54, 97, 66
])

# Employee salaries
salary = np.array([
    25000, 32000, 45000, 60000, 72000,
    85000, 40000, 52000, 90000, 31000,
    68000, 47000, 75000, 83000, 39000
])

# Monthly sales
sales = np.array([
    1200, 1450, 1320, 1680,
    1750, 1900, 2100, 2050,
    1980, 2200, 2400, 2600
])

# Customer IDs with duplicates
customer_ids = np.array([
    101, 102, 103, 104, 101,
    105, 106, 107, 102, 108,
    109, 110, 110, 111, 112
])

# A 2D marks matrix
class_marks = np.array([
    [78, 65, 91, 45, 82],
    [56, 99, 73, 68, 88],
    [59, 77, 84, 93, 61],
    [70, 80, 54, 97, 66]
])

# Small practice array
arr = np.array([12, 5, 18, 5, 9, 21, 12, 7, 18, 3])

## 4. Warm-up — 10 Problems

Start with direct use of functions you already know.

### Problem 1

Find the highest mark in `marks` using `np.max()`.

In [15]:
marks
np.max(marks)

np.int64(99)

### Problem 2

Find the lowest mark in `marks` using `np.min()`.

In [16]:
np.min(marks)

np.int64(45)

### Problem 3

Find the index of the highest mark using `np.argmax()`.

In [17]:
np.argmax(marks)

np.int64(6)

### Problem 4

Find the index of the lowest mark using `np.argmin()`.

In [18]:
np.argmin(marks)

np.int64(3)

### Problem 5

Sort `marks` in ascending order using `np.sort()`.

In [19]:
np.sort(marks)

array([45, 54, 56, 59, 61, 65, 66, 68, 70, 73, 77, 78, 80, 82, 84, 88, 91,
       93, 97, 99])

### Problem 6

Sort `salary` in ascending order using `np.sort()`.

In [20]:
np.sort(salary)

array([25000, 31000, 32000, 39000, 40000, 45000, 47000, 52000, 60000,
       68000, 72000, 75000, 83000, 85000, 90000])

### Problem 7

Find all unique values in `arr` using `np.unique()`.

In [21]:
np.unique(arr)

array([ 3,  5,  7,  9, 12, 18, 21])

### Problem 8

Find the total sales using `np.sum()`.

In [22]:
np.sum(sales)

np.int64(22630)

### Problem 9

Find the average mark using `np.mean()`.

In [23]:
np.mean(marks)

np.float64(74.3)

### Problem 10

Find the median mark using `np.median()`.

In [24]:
np.median(marks)

np.float64(75.0)

## 5. Core Practice — 15 Problems

Now combine sorting, statistics, indexing, slicing, Boolean indexing and uniqueness.

### Problem 11

Create `sorted_marks` from `marks` in ascending order. Then display the last 5 values of `sorted_marks` to get the five highest marks.

In [25]:
sorted_marks = np.sort(marks)
sorted_marks[-1:-6:-1]

array([99, 97, 93, 91, 88])

### Problem 12

Create `sorted_salary` from `salary` in ascending order. Then display the first 3 values to get the three lowest salaries.

In [26]:
sorted_salary = np.sort(salary)
sorted_salary[0:3]

array([25000, 31000, 32000])

### Problem 13

Find the five highest sales values from `sales` using `np.sort()` and slicing.

In [27]:
sorted_sales = np.sort(sales)
sorted_sales[-1:-6:-1]

array([2600, 2400, 2200, 2100, 2050])

### Problem 14

Find the five lowest sales values from `sales` using `np.sort()` and slicing.

In [28]:
sorted_salary[0:6]

array([25000, 31000, 32000, 39000, 40000, 45000])

### Problem 15

Find all students who scored above 80 using Boolean indexing.

In [29]:
marks[marks>80]

array([91, 82, 99, 88, 84, 93, 97])

### Problem 16

Find all salaries greater than or equal to 60000 using Boolean indexing.

In [30]:
salary[salary>=60000]

array([60000, 72000, 85000, 90000, 68000, 75000, 83000])

### Problem 17

Find all sales values below the average sales.

In [31]:
sales[sales<np.mean(sales)]

array([1200, 1450, 1320, 1680, 1750])

### Problem 18

Find the number of unique customer IDs using `np.unique()` and `.size`.

In [32]:
np.unique(customer_ids).size

12

### Problem 19

Find the unique customer IDs from `customer_ids` and display them in sorted order.

In [33]:
np.sort(np.unique(customer_ids))

array([101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112])

### Problem 20

Find the number of duplicate entries in `customer_ids` by comparing the total number of IDs with the number of unique IDs.

In [34]:
customer_ids.size - np.unique(customer_ids).size

3

### Problem 21

Calculate the range of the marks: maximum mark minus minimum mark.

In [35]:
# np.arange(np.max(marks),(np.max(marks)-np.min(marks)))
np.max(marks) - np.min(marks)

np.int64(54)

### Problem 22

Calculate the difference between the highest salary and lowest salary.

In [36]:
np.max(salary) - np.min(salary)

np.int64(65000)

### Problem 23

Calculate the mean, median and standard deviation of `sales`.

In [37]:
np.mean(sales),np.median(sales),np.std(sales)

(np.float64(1885.8333333333333),
 np.float64(1940.0),
 np.float64(407.8696346737385))

### Problem 24

Find the index of the month with the highest sales using `np.argmax(sales)` and the index of the month with the lowest sales using `np.argmin(sales)`.

In [38]:
np.argmax(sales),np.argmin(sales)

(np.int64(11), np.int64(0))

### Problem 25

Square every value in `arr`, then calculate the square root of the squared array.

In [39]:
arr
arr = arr ** 2
arr = arr ** (1/2)
arr

array([12.,  5., 18.,  5.,  9., 21., 12.,  7., 18.,  3.])

## 6. Real-World Practice — 10 Problems

These problems use the same NumPy skills in simple real-world situations.

### Problem 26

Student Performance: Find the top 5 marks from `marks` and calculate their average.

In [42]:
top = sorted_marks[-1:-6:-1]
np.mean(top)

np.float64(93.6)

### Problem 27

Student Performance: Find all marks below 50 and calculate how many students are in this group using `.size`.

In [45]:
marks[marks<50].size

1

### Problem 28

Salary Analysis: Find the average salary and then display all salaries above the average.

In [46]:
avg_salary = np.mean(salary)
salary[salary>avg_salary]

array([60000, 72000, 85000, 90000, 68000, 75000, 83000])

### Problem 29

Salary Analysis: Find the highest and lowest salaries and calculate the salary range.

In [50]:
print(np.max(salary))
print(np.min(salary))
np.max(salary) - np.min(salary)

90000
25000


np.int64(65000)

### Problem 30

Sales Analysis: Sort `sales` in ascending order and calculate the average of the three highest sales.

In [52]:
np.mean(sorted_sales[-1:-4:-1])

np.float64(2400.0)

### Problem 31

Sales Analysis: Find all months whose sales are greater than 2000 using Boolean indexing.

In [53]:
sales[sales>2000]

array([2100, 2050, 2200, 2400, 2600])

### Problem 32

Customer Analysis: Find the unique customer IDs and determine how many customer records are duplicates.

In [57]:
customer_ids.size - np.unique(customer_ids).size

3

### Problem 33

Data Cleaning: Create a sorted array containing only the unique values from `customer_ids`.

In [59]:
customer_sorted = np.unique(np.sort(customer_ids))
customer_sorted

array([101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112])

### Problem 34

Marks Transformation: Create a copy of `marks`, add 5 to every value, and use `np.clip` only if you already know it; otherwise cap values at 100 using Boolean indexing and assignment. Do not use loops.

In [198]:
original_marks = marks.copy()
original_marks + 5
np.clip(original_marks)

array([78, 65, 91, 45, 82, 56, 99, 73, 68, 88, 59, 77, 84, 93, 61, 70, 80,
       54, 97, 66])

### Problem 35

Error Analysis: Create an array of absolute differences between each student's mark and the average mark using `np.abs()` and vectorized operations.

In [204]:
st_arr = np.abs(original_marks,marks)
st_arr 

array([78, 65, 91, 45, 82, 56, 99, 73, 68, 88, 59, 77, 84, 93, 61, 70, 80,
       54, 97, 66])

## 7. Hard Problems — 5 Problems

These combine several concepts, but they still use only functions and techniques you have already studied.

### Problem 36

Create a sorted copy of `marks`. Extract the top 5 marks, bottom 5 marks, and calculate the difference between the average of the top 5 and the average of the bottom 5.

In [206]:
sorted_marks = np.sort(marks)
print(sorted_marks[0:6],sorted_marks[-1:-6:-1])
np.mean(sorted_marks[0:6]) - np.mean(sorted_marks[-1:-6:-1])

[45 54 56 59 61 65] [99 97 93 91 88]


np.float64(-36.93333333333333)

### Problem 37

Using `class_marks`, calculate the sum of each row and the sum of each column using `np.sum()` with the correct axis.

In [210]:
class_marks
print(np.sum(class_marks,axis=0))
np.sum(class_marks,axis=1)

[263 321 302 303 297]


array([361, 384, 374, 367])

### Problem 38

Using `class_marks`, find the maximum value of the entire matrix, the index of the maximum value in the flattened array, and the minimum value of the entire matrix.

In [212]:
class_marks
print(np.max(class_marks))
print(np.argmax(class_marks.flatten()))
print(np.min(class_marks))


99
6
45


### Problem 39

Normalize the `sales` array using the formula `(sales - mean) / std` and verify the result using `np.mean()` and `np.std()`.

In [221]:
sales_copy = sales.copy()
sales_copy = (sales_copy - sales_copy.mean())/np.std(sales_copy)
sales_copy
print(np.mean(sales_copy))
print(np.std(sales_copy))


2.0354088784794536e-16
0.9999999999999999


### Problem 40

Create a clean analysis of `marks`: sorted marks, unique marks, mean, median, standard deviation, highest mark, lowest mark, and the indices of the highest and lowest marks. Use no loops.

In [222]:
print(np.sort(marks))
print(np.unique(marks))
print(np.mean(marks))
print(np.median(marks))
print(np.std(marks))
print(np.max(marks))
print(np.min(marks))
print(np.argmax(marks))
print(np.argmin(marks))

[45 54 56 59 61 65 66 68 70 73 77 78 80 82 84 88 91 93 97 99]
[45 54 56 59 61 65 66 68 70 73 77 78 80 82 84 88 91 93 97 99]
74.3
75.0
14.798986451781081
99
45
6
3


## 8. 🏆 Boss Challenge — Student Performance Analysis

Use **NumPy only**. Do not use Pandas or Python loops.

You are given the `marks` array.

Complete all of the following:

1. Find the total number of students.
2. Find the highest and lowest marks.
3. Find the average and median marks.
4. Find the standard deviation and variance.
5. Create a sorted copy of the marks.
6. Extract the top 5 marks.
7. Extract the bottom 5 marks.
8. Find all students scoring above the average.
9. Find all students scoring below the average.
10. Find the index of the topper.
11. Find the index of the lowest scorer.
12. Find the range between the highest and lowest mark.
13. Create an array containing the absolute difference of every mark from the average.
14. Create a final summary using only NumPy operations.

### Rule
Do not use:
- Python `for` loops
- Pandas
- functions that have not been taught yet

The goal is to combine what you already know, not to learn something new.

In [ ]:
print(marks.size)
print(np.max(marks),np.min(marks))
print(np.mean(marks),np.median(marks))
print(np.std(marks),np.var(marks))
sorted_copy_marks = np.sort(marks).copy()
print(sorted_copy_marks[-1:-6:-1])
print(sorted_copy_marks[1:6:])
print(marks[marks>marks.mean()])
print(marks[marks<marks.mean()])
print(np.argmax(marks))
print(np.argmin(marks))
print(np.max(marks) - np.min(marks))
abs_marks = marks - np.mean(marks)
np.abs(abs_marks)


20
99 45
74.3 75.0
14.798986451781081 219.01
[99 97 93 91 88]
[54 56 59 61 65]
[78 91 82 99 88 77 84 93 80 97]
[65 45 56 73 68 59 61 70 54 66]
6
3
54


array([ 3.7,  9.3, 16.7, 29.3,  7.7, 18.3, 24.7,  1.3,  6.3, 13.7, 15.3,
        2.7,  9.7, 18.7, 13.3,  4.3,  5.7, 20.3, 22.7,  8.3])

## 9. 🎤 Interview Questions

Answer these in your own words before checking any reference.

1. What is the difference between `np.sort()` and changing the original array?
2. What is the difference between `np.max()` and `np.argmax()`?
3. What is the difference between `np.min()` and `np.argmin()`?
4. Why is Boolean indexing useful in data analysis?
5. What does `np.unique()` do, and where could it be useful in real-world data?

## 10. 📝 Reflection

- Hardest problem:
- Function I need to revise:
- One mistake I made:
- One concept I now understand better:
- Confidence level (1–10):
- What I should practice again: