In [1]:
a = 10
a

10

In [ ]:
import numpy as np
import pandas as pd

In [5]:
df = pd.read_csv("raw_data.csv")
df

,id,name,age,country,gender,income
0,1,John Doe,29.0,USA,Male,55000.0
1,1,John Doe,29.0,USA,Male,55000.0
2,2,Jane Smith,NaN,Canada,Female,62000.0
3,3,Alex,NaN,USA,Unknown,47000.0
4,4,Maria Garcia,34.0,Spain,Female,NaN
5,5,Li Wei,27.0,China,Male,51000.0
6,6,NaN,45.0,India,Female,73000.0
7,7,Ahmed Khan,38.0,NaN,Male,68000.0
8,8,Rachel Lee,29.0,USA,Female,62000.0
9,9,Carlos Ruiz,NaN,Mexico,Male,45000.0


# NumPy & Pandas Practice Questions
### 60 Questions — Basic to Advanced (5 Levels Each)

### Level 1 — Basics (Q1–Q6)

1. Import numpy as `np` and create a 1D array of integers from 1 to 10.

In [2]:
import numpy as np
arr = np.array([1,2,3,4,8,9])
arr

array([1, 2, 3, 4, 8, 9])

2. Create a 3×3 array filled with zeros, and another 3×3 array filled with ones.

In [5]:
arr_zero = np.zeros((3,3),dtype="int64")
arr_zero

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

3. For the array `np.array([[1,2,3],[4,5,6]])`, find its shape, number of dimensions (`ndim`), total size, and data type (`dtype`).

In [20]:
arr = np.array([[1,2,3],[4,5,6]])
print(np.shape(arr))
print(np.ndim(arr))
print(type(arr))

(2, 3)
2
<class 'numpy.ndarray'>


4. Create an array of 10 evenly spaced numbers between 0 and 5 using `np.linspace`.

In [21]:
arr = np.linspace(0,5,10)
arr

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

5. Create an array with values from 0 to 20 with a step of 2 using `np.arange`.

In [24]:
arr = np.arange(0,20,2)
arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

6. For `arr = np.array([10,20,30,40,50])`, access the 3rd element and the last element (without hardcoding its position as 4).

In [25]:
arr = np.array([10,20,30,40,50])
index = [2,4]
arr[index]

array([30, 50])


### Level 2 — Basic Operations (Q7–Q12)

7. Reshape a 1D array of 12 elements into a 3×4 matrix.

In [41]:
arr_2d = np.array([[1,2,3,4],[5,6,7,8],[9,0,10,11]])
print(arr_2d.flatten())
print(arr_2d.shape)

[ 1  2  3  4  5  6  7  8  9  0 10 11]
(3, 4)


8. Given `arr = np.array([1,2,3,4,5])`, multiply every element by 3 and add 1 — using vectorized operations, no loop.

In [40]:
arr = np.array([1,2,3,4,5])
arr*3 + 1


array([ 4,  7, 10, 13, 16])

9. From a 2D array of shape (5,5), slice out the first two rows and the last two columns.

In [10]:
arr_2d = np.array([
    [3, 7, 1, 0, 9],
    [4, 2, 8, 6, 5],
    [1, 0, 3, 7, 2],
    [9, 8, 4, 6, 1],
    [5, 2, 0, 3, 7]
])
arr_2d[0:2,3:6]

array([[0, 9],
       [6, 5]])

10. Create two arrays of the same shape and perform element-wise addition, subtraction, multiplication, and division between them.

In [85]:
arr_2d1 = np.array([
    [6, 1, 4, 8, 9],
    [2, 0, 7, 3, 5],
    [1, 9, 6, 2, 4],
    [8, 3, 0, 7, 1],
    [5, 2, 9, 6, 0]
])
print("Addtion:-\n")
print(arr_2d + arr_2d1)
print("multiplication:-\n")
print(arr_2d * arr_2d1)
print("Subtraction:-\n")
print(arr_2d - arr_2d1)
print("Division:-\n")
print(arr_2d / arr_2d1)


Addtion:-

[[ 9  8  5  8 18]
 [ 6  2 15  9 10]
 [ 2  9  9  9  6]
 [17 11  4 13  2]
 [10  4  9  9  7]]
multiplication:-

[[18  7  4  0 81]
 [ 8  0 56 18 25]
 [ 1  0 18 14  8]
 [72 24  0 42  1]
 [25  4  0 18  0]]
Subtraction:-

[[-3  6 -3 -8  0]
 [ 2  2  1  3  0]
 [ 0 -9 -3  5 -2]
 [ 1  5  4 -1  0]
 [ 0  0 -9 -3  7]]
Division:-

[[0.5        7.         0.25       0.         1.        ]
 [2.                inf 1.14285714 2.         1.        ]
 [1.         0.         0.5        3.5        0.5       ]
 [1.125      2.66666667        inf 0.85714286 1.        ]
 [1.         1.         0.         0.5               inf]]


C:\Users\inzam\AppData\Local\Temp\ipykernel_6832\3421028756.py:15: RuntimeWarning: divide by zero encountered in divide
  print(arr_2d / arr_2d1)


11. Find the transpose of a 2D array using both `.T` and `np.transpose()`.

In [88]:
print(np.transpose(arr_2d))
print(arr_2d.T)

[[3 4 1 9 5]
 [7 2 0 8 2]
 [1 8 3 4 0]
 [0 6 7 6 3]
 [9 5 2 1 7]]
[[3 4 1 9 5]
 [7 2 0 8 2]
 [1 8 3 4 0]
 [0 6 7 6 3]
 [9 5 2 1 7]]


12. Create a random array of shape (4,4) with values between 0 and 1 using `np.random.rand`.

In [96]:
rand_arr = np.random.rand(4,4)
rand_arr

array([[0.21605823, 0.40427159, 0.18526406, 0.07097218],
       [0.37600447, 0.29559578, 0.8518825 , 0.15419116],
       [0.15396299, 0.1775799 , 0.05660288, 0.16542349],
       [0.37108052, 0.14678293, 0.32985807, 0.30147744]])

### Level 3 — Intermediate (Q13–Q18)

13. Given an array of exam scores, use boolean indexing to extract only the scores above 60.

In [7]:
marks = np.random.randint(13,99,25)
marks[marks>60]

array([75, 95, 78, 63, 64, 83, 79, 88, 93, 87], dtype=int32)

14. For a 2D array, compute sum, mean, median, standard deviation, min, and max — once for the whole array, once along `axis=0`, and once along `axis=1`. Explain in your own words what axis=0 vs axis=1 means.

In [19]:
arr_2d1 = np.array([
    [6, 1, 4, 8, 9],
    [2, 0, 7, 3, 5],
    [1, 9, 6, 2, 4],
    [8, 3, 0, 7, 1],
    [5, 2, 9, 6, 0]
])
print("Whole Array Statistics:-")
print("Sum of Whole Array", arr_2d.sum())
print("Mean of Whole Array", arr_2d.mean())
print("Median of Whole Array", np.median(arr_2d))
print("Standard Deviation of Whole Array", arr_2d.std())
print("Minimum Number of Whole Array", arr_2d.min())
print("Maximum Number of Whole Array", arr_2d.max())
print("Along the columns:-")
print("Sum Along the columns",arr_2d.sum(axis=0))
print("mean Along the columns",arr_2d.mean(axis=0))
print("std_dev Along the columns",arr_2d.std(axis=0))
print("Min number Along the columns",arr_2d.min(axis=0))
print("Max number Along the columns",arr_2d.min(axis=0))
print("Along the rows:-")
print("Sum Along the rows:", arr_2d.sum(axis=1))
print("Mean Along the rows:", arr_2d.mean(axis=1))
print("Std Dev Along the rows:", arr_2d.std(axis=1))
print("Min Number Along the rows:", arr_2d.min(axis=1))
print("Max Number Along the rows:", arr_2d.max(axis=1))



Whole Array Statistics:-
Sum of Whole Array 103
Mean of Whole Array 4.12
Median of Whole Array 4.0
Standard Deviation of Whole Array 2.888875213642846
Minimum Number of Whole Array 0
Maximum Number of Whole Array 9
Along the columns:-
Sum Along the columns [22 19 16 22 24]
mean Along the columns [4.4 3.8 3.2 4.4 4.8]
std_dev Along the columns [2.65329983 3.12409987 2.78567766 2.57681975 2.99332591]
Min number Along the columns [1 0 0 0 1]
Max number Along the columns [1 0 0 0 1]
Along the rows:-
Sum Along the rows: [20 25 13 28 17]
Mean Along the rows: [4.  5.  2.6 5.6 3.4]
Std Dev Along the rows: [3.46410162 2.         2.41660919 2.87054002 2.41660919]
Min Number Along the rows: [0 2 0 1 0]
Max Number Along the rows: [9 8 7 9 7]


15. Demonstrate broadcasting: add a 1D array of shape (3,) to a 2D array of shape (4,3).

In [ ]:
arr1 = np.array([1,2,3])
arr2 = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
    [10, 11, 12]
])
print(np.shape(arr1))
print(np.shape(arr2))
arr1 + arr2

(3,)
(4, 3)


array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12],
       [11, 13, 15]])

16. Use `np.where()` to replace all negative values in an array with 0.

In [39]:
arr2 = np.array([
    [1, -2, 3],
    [-4, 5, 6],
    [7, -8, -9],
    [10, 11, -12]
])
np.where(arr2<0 , 0 , arr2) 

array([[ 1,  0,  3],
       [ 0,  5,  6],
       [ 7,  0,  0],
       [10, 11,  0]])

17. Stack two 1D arrays vertically and horizontally using `np.vstack` and `np.hstack`.

In [47]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
print(np.vstack((arr1,arr2)))
print(np.hstack((arr1,arr2)))

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


18. Sort a 2D array along each row, and separately, along each column.

In [58]:
arr2 = np.array([
    [6, 1, 4, 8, 9],
    [2, 0, 7, 3, 5],
    [1, 9, 6, 2, 4],
    [8, 3, 0, 7, 1],
    [5, 2, 9, 6, 0]
])
print(np.sort(arr2,axis=0))
print(np.sort(arr2,axis=1))

[[1 0 0 2 0]
 [2 1 4 3 1]
 [5 2 6 6 4]
 [6 3 7 7 5]
 [8 9 9 8 9]]
[[1 4 6 8 9]
 [0 2 3 5 7]
 [1 2 4 6 9]
 [0 1 3 7 8]
 [0 2 5 6 9]]


In [ ]:
sales = np.array([450,520,610,710,480,560,590])
print(np.sum(sales))#Total Sales
print(np.mean(sales))# Average Sales
print(np.max(sales))# Highest Sale
print(np.min(sales))# Lowest Sale

3920
560.0
710
450
